files:
  - source: /assets/locales/en/*.json
    translation: /assets/locales/%two_letters_code%/%original_file_name%
commit_message: '[ci skip]' # appends to default commit message and skips unnecessary ci work
pull_request_labels:
  - crowdin
  - l10n
