import { ComponentStory, ComponentMeta } from '@storybook/react';

import NodeRequirements from '../renderer/Presentational/NodeRequirements/NodeRequirements';

// More on default export: https://storybook.js.org/docs/react/writing-stories/introduction#default-export
export default {
  title: 'Example/NodeRequirements',
  component: NodeRequirements,
  // More on argTypes: https://storybook.js.org/docs/react/api/argtypes
  argTypes: {
  },
} as ComponentMeta<typeof NodeRequirements>;

// More on component templates: https://storybook.js.org/docs/react/writing-stories/introduction#using-args
const Template: ComponentStory<typeof NodeRequirements> = (args) => <NodeRequirements {...args} />;

export const Primary = Template.bind({});
// More on args: https://storybook.js.org/docs/react/writing-stories/args
Primary.args = {
  nodeRequirements: {
    documentationUrl: 'https://www.nicenode.xyz/#requirements',
    description: 'Your system is checked with the recommended requirements for the selected clients. You are able to launch a node with lower specifications but expect some hickups now and then.',
    cpu: {
      cores: 4,
      minSpeed: 2.4
    },
    memory: {
      minSize: 8000000000
    },
    storage: {
      minSize: 1000,
      minWriteSpeed: 400,
      ssdRequired: true
    },
    internet: {
      minDownloadSpeed: 25,
      minUploadSpeed: 3,
    },
    docker: {
      required: true,
      minVersion: '20.10',
    }
  },
  systemData: {
    version: '5.11.15',
    system: {
      manufacturer: 'Apple Inc.',
      model: 'MacBookPro18,1',
      version: '',
      serial: 'ABCDEFGH',
      uuid: '1234567-a1b2c-34gz-345g-453gsfd3',
      sku: '',
      virtual: false
    },
    bios: {
      vendor: 'Apple Inc.',
      version: '7459.141.1',
      releaseDate: '',
      revision: ''
    },
    baseboard: {
      manufacturer: 'Apple Inc.',
      model: 'MacBookPro18,1',
      version: '',
      serial: 'ABCDEFGH',
      assetTag: '',
      memMax: 17179869184,
      memSlots: 0
    },
    chassis: {
      manufacturer: 'Apple Inc.',
      model: 'MacBookPro18,1',
      type: '',
      version: '',
      serial: 'ABCDEFGH',
      assetTag: '',
      sku: ''
    },
    os: {
      platform: 'darwin',
      distro: 'macOS',
      release: '12.6',
      codename: 'macOS Monterey',
      kernel: '21.6.0',
      arch: 'arm64',
      hostname: 'Nice-MacBook-Pro.local',
      fqdn: 'Nice-MacBook-Pro.local',
      codepage: 'UTF-8',
      logofile: 'darwin',
      serial: 'A-NICE-SERIAL',
      build: '21G115',
      servicepack: '',
      uefi: true
    },
    uuid: {
      os: '1234567-a1b2c-34gz-345g-453gsfd3',
      hardware: 'ABCDEFGH',
      macs: [
        'bc:d0:74:52:3f:db',
        'da:7b:71:78:0a:9e',
        'da:7b:71:78:0a:9f',
        'da:7b:71:78:0a:a0',
        'fe:e4:6d:79:19:97'
      ]
    },
    versions: {
      kernel: '21.6.0',
      openssl: '1.1.1',
      systemOpenssl: '2.8.3',
      systemOpensslLib: 'LibreSSL',
      node: '16.9.1',
      v8: '9.6.180.23-electron.0',
      npm: '8.18.0',
      yarn: '',
      pm2: '5.2.0',
      gulp: '',
      grunt: '',
      git: '2.37.0',
      tsc: '4.6.4',
      mysql: '',
      redis: '',
      mongodb: '',
      apache: '2.4.54',
      nginx: '',
      php: '',
      docker: '20.10.17',
      postfix: '3.2.2',
      postgresql: '',
      perl: '5.30.3',
      python: '',
      python3: '3.9.6',
      pip: '',
      pip3: '21.2.4',
      java: '',
      gcc: '14.0.0',
      virtualbox: '',
      bash: '3.2.57',
      zsh: '5.8.1',
      fish: '',
      powershell: '',
      dotnet: ''
    },
    cpu: {
      manufacturer: 'Apple',
      brand: 'M1 Pro',
      vendor: 'Apple',
      family: '458787763',
      model: '',
      stepping: '4',
      revision: '',
      voltage: '',
      speed: 2.4,
      speedMin: 2.4,
      speedMax: 2.4,
      governor: '',
      cores: 10,
      physicalCores: 10,
      processors: 1,
      socket: 'SOC',
      flags: '',
      virtualization: false,
      cache: { l1d: 131072, l1i: 65536, l2: 4194304, l3: null },
      efficiencyCores: 2,
      performanceCores: 8
    },
    graphics: { controllers: [ [Object] ], displays: [ [Object] ] },
    net: [
      {
        iface: 'lo0',
        ifaceName: 'lo0',
        default: false,
        ip4: '127.0.0.1',
        ip4subnet: '255.0.0.0',
        ip6: '::1',
        ip6subnet: 'ffff:ffff:ffff:ffff::',
        mac: '',
        internal: true,
        virtual: false,
        operstate: 'down',
        type: 'wired',
        duplex: 'full',
        mtu: 16384,
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'anpi1',
        ifaceName: 'anpi1',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: 'fe80::d87b:71ff:fe78:a9f',
        ip6subnet: 'ffff:ffff:ffff:ffff::',
        mac: 'da:7b:71:78:0a:9f',
        internal: false,
        virtual: false,
        operstate: 'up',
        type: 'wired',
        duplex: 'full',
        mtu: 1500,
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'anpi0',
        ifaceName: 'anpi0',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: 'fe80::d87b:71ff:fe78:a9e',
        ip6subnet: 'ffff:ffff:ffff:ffff::',
        mac: 'da:7b:71:78:0a:9e',
        internal: false,
        virtual: false,
        operstate: 'up',
        type: 'wired',
        duplex: 'full',
        mtu: 1500,
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'anpi2',
        ifaceName: 'anpi2',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: 'fe80::d87b:71ff:fe78:aa0',
        ip6subnet: 'ffff:ffff:ffff:ffff::',
        mac: 'da:7b:71:78:0a:a0',
        internal: false,
        virtual: false,
        operstate: 'up',
        type: 'wired',
        duplex: 'full',
        mtu: 1500,
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'ap1',
        ifaceName: 'ap1',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: '',
        ip6subnet: '',
        mac: 'be:d0:74:52:3f:db',
        internal: false,
        virtual: false,
        operstate: 'up',
        type: 'wireless',
        duplex: 'full',
        mtu: 1500,
        speed: 10,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'en4',
        ifaceName: 'en4',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: '',
        ip6subnet: '',
        mac: 'da:7b:71:78:0a:7e',
        internal: false,
        virtual: false,
        operstate: 'up',
        type: 'wired',
        duplex: 'full',
        mtu: 1500,
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'en5',
        ifaceName: 'en5',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: '',
        ip6subnet: '',
        mac: 'da:7b:71:78:0a:7f',
        internal: false,
        virtual: false,
        operstate: 'up',
        type: 'wired',
        duplex: 'full',
        mtu: 1500,
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'en6',
        ifaceName: 'en6',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: '',
        ip6subnet: '',
        mac: 'da:7b:71:78:0a:80',
        internal: false,
        virtual: false,
        operstate: 'up',
        type: 'wired',
        duplex: 'full',
        mtu: 1500,
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'en0',
        ifaceName: 'en0',
        default: true,
        ip4: '10.232.186.99',
        ip4subnet: '255.255.248.0',
        ip6: 'fe80::34:2853:c844:e53a',
        ip6subnet: 'ffff:ffff:ffff:ffff::',
        mac: 'bc:d0:74:52:3f:db',
        internal: false,
        virtual: false,
        operstate: 'up',
        type: 'wireless',
        duplex: 'full',
        mtu: 1500,
        speed: 20.27,
        dhcp: true,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'en1',
        ifaceName: 'en1',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: '',
        ip6subnet: '',
        mac: '36:23:b8:2e:a0:00',
        internal: false,
        virtual: false,
        operstate: 'up',
        type: 'wired',
        duplex: 'full',
        mtu: 1500,
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'en2',
        ifaceName: 'en2',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: '',
        ip6subnet: '',
        mac: '36:23:b8:2e:a0:04',
        internal: false,
        virtual: false,
        operstate: 'up',
        type: 'wired',
        duplex: 'full',
        mtu: 1500,
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'en3',
        ifaceName: 'en3',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: '',
        ip6subnet: '',
        mac: '36:23:b8:2e:a0:08',
        internal: false,
        virtual: false,
        operstate: 'up',
        type: 'wired',
        duplex: 'full',
        mtu: 1500,
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'awdl0',
        ifaceName: 'awdl0',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: 'fe80::fce4:6dff:fe79:1997',
        ip6subnet: 'ffff:ffff:ffff:ffff::',
        mac: 'fe:e4:6d:79:19:97',
        internal: false,
        virtual: false,
        operstate: 'up',
        type: 'wireless',
        duplex: 'full',
        mtu: 1500,
        speed: 10,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'bridge0',
        ifaceName: 'bridge0',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: '',
        ip6subnet: '',
        mac: '36:23:b8:2e:a0:00',
        internal: false,
        virtual: false,
        operstate: 'up',
        type: 'wired',
        duplex: 'full',
        mtu: 1500,
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'llw0',
        ifaceName: 'llw0',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: 'fe80::fce4:6dff:fe79:1997',
        ip6subnet: 'ffff:ffff:ffff:ffff::',
        mac: 'fe:e4:6d:79:19:97',
        internal: false,
        virtual: false,
        operstate: 'up',
        type: 'wireless',
        duplex: 'full',
        mtu: 1500,
        speed: 229,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'utun0',
        ifaceName: 'utun0',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: 'fe80::ff3a:6529:83b1:d969',
        ip6subnet: 'ffff:ffff:ffff:ffff::',
        mac: '',
        internal: false,
        virtual: false,
        operstate: 'down',
        type: 'wired',
        duplex: 'full',
        mtu: 1380,
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'utun1',
        ifaceName: 'utun1',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: 'fe80::83e7:635d:8039:ed9f',
        ip6subnet: 'ffff:ffff:ffff:ffff::',
        mac: '',
        internal: false,
        virtual: false,
        operstate: 'down',
        type: 'wired',
        duplex: 'full',
        mtu: 2000,
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'utun2',
        ifaceName: 'utun2',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: 'fe80::ce81:b1c:bd2c:69e',
        ip6subnet: 'ffff:ffff:ffff:ffff::',
        mac: '',
        internal: false,
        virtual: false,
        operstate: 'down',
        type: 'wired',
        duplex: 'full',
        mtu: 1000,
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'utun3',
        ifaceName: 'utun3',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: 'fe80::4781:682a:d65a:704a',
        ip6subnet: 'ffff:ffff:ffff:ffff::',
        mac: '',
        internal: false,
        virtual: false,
        operstate: 'down',
        type: 'wired',
        duplex: 'full',
        mtu: 1380,
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'utun4',
        ifaceName: 'utun4',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: 'fe80::185c:ef7a:abe4:6f61',
        ip6subnet: 'ffff:ffff:ffff:ffff::',
        mac: '',
        internal: false,
        virtual: false,
        operstate: 'down',
        type: 'wired',
        duplex: 'full',
        mtu: 1380,
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'utun5',
        ifaceName: 'utun5',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: 'fe80::f702:bc5b:af1f:2998',
        ip6subnet: 'ffff:ffff:ffff:ffff::',
        mac: '',
        internal: false,
        virtual: false,
        operstate: 'down',
        type: 'wired',
        duplex: 'full',
        mtu: 1380,
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      },
      {
        iface: 'utun6',
        ifaceName: 'utun6',
        default: false,
        ip4: '',
        ip4subnet: '',
        ip6: 'fe80::7db8:b351:9e07:44fb',
        ip6subnet: 'ffff:ffff:ffff:ffff::',
        mac: '',
        internal: false,
        virtual: false,
        operstate: 'down',
        type: 'wired',
        duplex: 'full',
        mtu: 1380,
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: '',
        ieee8021xState: '',
        carrierChanges: 0
      }
    ],
    memLayout: [
      {
        size: 17179869184,
        bank: '0',
        type: 'LPDDR5',
        ecc: false,
        clockSpeed: 0,
        formFactor: '',
        manufacturer: 'Apple',
        partNum: '',
        serialNum: '',
        voltageConfigured: null,
        voltageMin: null,
        voltageMax: null
      }
    ],
    diskLayout: [
      {
        device: 'disk0',
        type: 'NVMe',
        name: 'APPLE SSD AP0512R',
        vendor: 'Apple',
        size: 500277792768,
        bytesPerSector: null,
        totalCylinders: null,
        totalHeads: null,
        totalSectors: null,
        totalTracks: null,
        tracksPerCylinder: null,
        sectorsPerTrack: null,
        firmwareRevision: '387.140.',
        serialNum: '0ba0168944911e27',
        interfaceType: 'PCIe',
        smartStatus: 'Ok',
        temperature: null
      }
    ]
  }
};
