name: e2e-tests-specs

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e-build-n-test:
    environment: staging
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: 💚 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 🧱 Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y rpm libarchive-tools podman

      - name: 📦 Bundle Application
        env:
          DEBUG: "*electron*"
          SENTRY_DSN: fake-token
          MP_PROJECT_TOKEN: fake-token
          MP_PROJECT_ENV: dev
          NICENODE_ENV: test
          NO_CODE_SIGNING: true
        run: |
          podman build -t podman-fedora-wdio -f ./test/podman-fedora-wdio.dockerfile .

      - name: 🧪 Run Tests
        run: |
          podman run --rm -v ./:/home/podman/nice-node -u podman podman-fedora-wdio

